[build]
  command = "npm run build"
  publish = "dashboard/build"

[[plugins]]
  package = "@netlify/plugin-local-install-core"
  [plugins.inputs]
    preinstall = "curl https://sh.rustup.rs -sSf | sh -s -- -y && export PATH=$HOME/.cargo/bin:$PATH"